  const doctors = [
    { id: 1,
         name: "Dr. Ahmed Ali", 
         title: "Consultant", 
         specialist: "Cardiology", 
         image: "https://randomuser.me/api/portraits/men/32.jpg" },

    { id: 2, 
        name: "Dr. Fatima Mohamed", 
        title: "Senior Surgeon",
         specialist: "General Surgery",
         image: "https://randomuser.me/api/portraits/women/44.jpg" },

    { id: 3, 
     name: "Dr. Yusuf Abdullahi",
     title: "Consultant",
     specialist: "Neurology", 
     image: "https://randomuser.me/api/portraits/men/65.jpg" },
    { id: 4, 
        name: "Dr. Amina Hassan", 
        title: "Pediatrician",
         specialist: "Pediatrics", 
         image: "https://randomuser.me/api/portraits/women/68.jpg" },
    { id: 5,
         name: "Dr. Omar Warsame", title: "Consultant", specialist: "Orthopedics", image: "https://randomuser.me/api/portraits/men/12.jpg" },
    { id: 6,
         name: "Dr. Laila Noor",
          title: "Dermatologist", 
          specialist: "Dermatology", 
          image: "https://randomuser.me/api/portraits/women/22.jpg" },
    { id: 7, 
        name: "Dr. Mahad Yusuf",
         title: "ENT Specialist", 
         specialist: "Otolaryngology", 
         image: "https://randomuser.me/api/portraits/men/45.jpg" },
    { id: 8,
         name: "Dr. Sahra Mohamed",
          title: "Gynecologist", 
          specialist: "Obstetrics & Gynecology",
           image: "https://randomuser.me/api/portraits/women/55.jpg" },
    { id: 9, 
        name: "Dr. Abdi Noor", 
        title: "Radiologist", specialist: "Radiology",
         image: "https://randomuser.me/api/portraits/men/78.jpg" },
    { id: 10,
         name: "Dr. Hana Yusuf", 
         title: "Oncologist",
          specialist: "Oncology", 
          image: "https://randomuser.me/api/portraits/women/11.jpg" },
    { id: 11, 
        name: "Dr. Ismail Farah",
         title: "General Practitioner", 
         specialist: "General Medicine", 
         image: "https://randomuser.me/api/portraits/men/5.jpg" },
    { id: 12,
         name: "Dr. Nimo Ali", 
         title: "Endocrinologist", 
         specialist: "Endocrinology", 
         image: "https://randomuser.me/api/portraits/women/18.jpg" },
  ]