  const Cards = [
    { id: 1,
         name: "Dr.Ahmed Ali", 
         title: "Consultant", 
         specialist: "Cardiology", 
         image: "https://shaafihospital.so/uploads/kLM3apSh0LN6hiyXPdoIOReE6c0mNCYPZGOlTfgD.jpg" 
     },

    { id: 2, 
        name: "Dr.Mohamed", 
         title: "Cardiovascular Specialist",
    specialist: "Cardiology",
         image: "https://shaafihospital.so/uploads/qqsEYPdf3XzQvEKrDaSoWJs4fhsnRPAyL1Nh20eO.jpg"
      },

   { id: 3, 
     name: "Dr.Yusuf Abdullahi",
    title: "Heart Surgeon",
    specialist: "Cardiology", 
     image: "https://randomuser.me/api/portraits/men/65.jpg" },
    { id: 3, 
     name: "Dr.Yusuf Jeylani",
        title: "Pediatric Cardiologist",
    specialist: "Cardiology", 
          image: "https://shaafihospital.so/uploads/zY7UEHsCa5N4TjSnlQeiuV4MODApgk2yc04LZJD5.jpg" 
     },
    { id: 4, 
        name: "Dr.Shafi Mohamed", 
        title: "Heart Disease Specialist",
    specialist: "Cardiology",
         image: "https://shaafihospital.so/uploads/Jj1DaOtNEGHOX55knFxEGBRIN9L7HI6V3219Bi1m.jpg" 
     },
    { id: 5,
         name: "Dr.Omar Warsame", 
         title: "Neurosurgeon",
    specialist: "Neurology", 
         image: "https://randomuser.me/api/portraits/men/12.jpg" },
    { id: 6,
         name: "Dr.Laila Noor",
           title: "Neurophysiologist",
    specialist: "Neurology",
          image: "https://shaafihospital.so/uploads/IdgWeSnGgJikxdlySLzacp1fjQCOjABBHip4ckNk.jpg" },
    { id: 7, 
        name: "Dr.Mahad Yusuf",
       title: "Brain Specialist",
    specialist: "Neurology", 
         image: "https://shaafihospital.so/uploads/0f3DQH52eiM4VkreXm2ErxIKUpX5DeavLcB9Y9II.jpg" },
    { id: 8,
         name: "Dr.Jinow",
          title: "Spinal Disorder Expert",
    specialist: "Neurology",
           image: "https://shaafihospital.so/uploads/A6Y09qEzf1GQMg4KJDtIazqCVTwbbojFObaG2WjW.jpg" },
    { id: 9, 
        name: "Dr.Abdi Noor", 
         title: "Internal Medicine Specialist",
    specialist: "Medicine",
         image: "https://shaafihospital.so/uploads/tLQ6CiE441WU1DWl7uvShBKANhLAZu8oKrHdhtS5.jpg" },
    { id: 10,
         name: "Dr.Hanad Yusuf", 
         title: "Family Doctor",
    specialist: "Medicine",
          image: "https://shaafihospital.so/uploads/q4eg8vfH4nynIHFTsTPJ7DY8ksUGxQOKNzL5ET3s.jpg" },
    { id: 11, 
        name: "Dr.Ismail Farah",
         title: "Senior Physician",
    specialist: "Medicine", 
         image: "https://shaafihospital.so/uploads/yiSuyGbxqkoSsEaDngD3fMyo6TJCqq78Wxdz7IYw.jpg" },
    { id: 12,
         name: "Dr.Ali Bahir", 
        title: "Internal Medicine Specialist",
    specialist: "Medicine",
         image: "https://shaafihospital.so/uploads/IaMYvBLpBtMBDIBVlZbMOx6xAnij2TD4iaycijDH.jpg" },
  ]
  export default Cards